language: csharp
dist: trusty
notifications:
  email: never
mono: none
dotnet: 1.0.1
script:
  - dotnet restore -v Minimal
  - dotnet build ClubHouse/ClubHouse.csproj -c Release 
#  - dotnet test tests/SodaPop.ConfigExplorer.Tests.csproj