os: Visual Studio 2017
version: 1.1.{build}
configuration: Release
before_build:
- dotnet --info
build_script:
- dotnet restore -v Minimal
- dotnet build -c %CONFIGURATION%
after_build:
- dotnet pack -c %CONFIGURATION% .\ClubHouse\ClubHouse.csproj -o .\artifacts
test: off
artifacts:
- path: .\ClubHouse\artifacts\**\*.*
deploy:
- provider: NuGet
  api_key:
    secure: Gerln5x/jQ3CsCjXe76zQuP2Rjh12sKBH2wj88LIpt1IQym1+6MlFVWmvx5j+KSw
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: release