os: Visual Studio 2017
version: 1.0.{build}
configuration: Release
pull_requests:
  do_not_increment_build_number: true
environment:
  ASPNETCORE_ENVIRONMENT: Development
build:
  verbosity: minimal
  publish_nuget: true
build_script:
- dotnet restore -v Minimal
- dotnet build -c %CONFIGURATION%
- dotnet pack -c %CONFIGURATION% .\ClubHouse\ClubHouse.csproj -o .\artifacts 
test: off
artifacts:
- path: .\src\artifacts\**\*.*
deploy:
- provider: NuGet
  api_key:
    secure: Gerln5x/jQ3CsCjXe76zQuP2Rjh12sKBH2wj88LIpt1IQym1+6MlFVWmvx5j+KSw
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: release