os: Visual Studio 2017
version: 1.1.{build}
configuration: Release
init:
- ps: |
    if ($env:APPVEYOR_REPO_TAG -eq $true -and $env:APPVEYOR_REPO_TAG_NAME  -match "^v\d+\.\d+\.\d+$")
    {
        Write-Host "Tagged For Release: $($env:APPVEYOR_REPO_TAG_NAME)" -ForegroundColor Green
        $env:TaggedForRelease = $true
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME".Substring(1)
    }
before_build:
- dotnet --info
- dotnet restore
build_script:
- dotnet build -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%
after_build:
- dotnet pack -c %CONFIGURATION% .\ClubHouse\ClubHouse.csproj -o .\artifacts
test: off
artifacts:
- path: .\ClubHouse\artifacts\**\*.*
deploy:
- provider: NuGet
  api_key:
    secure: Gerln5x/jQ3CsCjXe76zQuP2Rjh12sKBH2wj88LIpt1IQym1+6MlFVWmvx5j+KSw
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    TaggedForRelease: true

- provider: GitHub
  release: $env:APPVEYOR_REPO_TAG_NAME
  description: 'Release of $(appveyor_build_version)'
  auth_token:
    secure: uLTEBGoagOuXDvbSbUqHe2k/7Oyk4lttpWKHBn4mRdSiZP6aCB9MMybins2dQLCZ
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  on:
    TaggedForRelease: true